### ISSUE TITLE
Sifis wp2 checklist

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/wp4-edge_ids#1]
Hi, here the usual wp2 checklist, please tick everything that is already addressed, feel free to ping me if you need help.

- [x] Does the project have a `README.md` ?
- [x] Does the project have a `LICENSE` file?
    - If possible use either [MIT](https://spdx.org/licenses/MIT) or other compatible licenses.
- [x] Does the project have a [GitHub Action](https://github.com/features/actions) (you may use [sifis-generate](https://crates.io/crates/sifis-generate) to create it)?
    - [x] Does it upload the code coverage somewhere?
    - [ ] Does it manage the release of the code? (Continuous Delivery)
- [x] Does it have a DockerFile or does it need it?

## Bonus track

- [ ] Does it use the standard cargo layout?
- [ ] Does it pass `cargo audit`?
- [ ] Will you deploy it to crates.io?
